use_frameworks!

target 'SSSheetLayout_Example' do
  pod 'SSSheetLayout', :path => '../'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end

  target 'SSSheetLayout_Tests' do
    inherit! :search_paths

    
  end
end
